import type { ActionConfig } from "@prooflayer/shared";

export const ACTIONS_LIST: ActionConfig[] = [
  {
    id: "reaping.cut_stalks",
    skillId: "reaping",
    name: "Cut aether stalks",
    description: "Slice low-growing stalks at the lattice edge.",
    levelRequired: 1,
    durationMs: 3000,
    xpReward: 10,
    goldReward: 1,
    drops: [{ itemId: "aether_stalk", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "reaping.pluck_blooms",
    skillId: "reaping",
    name: "Pluck dawn blooms",
    description: "Pinch flowers from their stems before they close.",
    levelRequired: 20,
    durationMs: 4500,
    xpReward: 32,
    goldReward: 4,
    drops: [{ itemId: "dawn_bloom", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "reaping.harvest_starflax",
    skillId: "reaping",
    name: "Harvest starflax",
    description: "Cut wide swaths of starflax — and watch for the silvered kind.",
    levelRequired: 60,
    durationMs: 6000,
    xpReward: 100,
    goldReward: 12,
    drops: [
      { itemId: "starflax", min: 1, max: 2, chance: 1 },
      { itemId: "silverflax", min: 1, max: 1, chance: 0.05 },
    ],
  },

  {
    id: "quarrying.dim_shards",
    skillId: "quarrying",
    name: "Chip dim shards",
    description: "Strike at a vein of pale crystal.",
    levelRequired: 1,
    durationMs: 3000,
    xpReward: 12,
    goldReward: 1,
    drops: [{ itemId: "dim_shard", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "quarrying.radiant_shards",
    skillId: "quarrying",
    name: "Cleave radiant shards",
    description: "Heavier swings into a brighter vein.",
    levelRequired: 30,
    durationMs: 4500,
    xpReward: 48,
    goldReward: 6,
    drops: [{ itemId: "radiant_shard", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "quarrying.prismatic_shards",
    skillId: "quarrying",
    name: "Quarry prismatic shards",
    description: "Patient work on the rarest sigil-vein.",
    levelRequired: 70,
    durationMs: 6000,
    xpReward: 120,
    goldReward: 15,
    drops: [{ itemId: "prismatic_shard", min: 1, max: 1, chance: 1 }],
  },

  {
    id: "tempering.dim_ingot",
    skillId: "tempering",
    name: "Press dim ingot",
    description: "Heat dim shards and beat them flat.",
    levelRequired: 1,
    durationMs: 4000,
    xpReward: 15,
    goldReward: 2,
    drops: [{ itemId: "dim_ingot", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "tempering.radiant_ingot",
    skillId: "tempering",
    name: "Press radiant ingot",
    description: "Higher heat. Brighter glow. Less forgiving.",
    levelRequired: 35,
    durationMs: 5000,
    xpReward: 55,
    goldReward: 8,
    drops: [{ itemId: "radiant_ingot", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "tempering.prismatic_ingot",
    skillId: "tempering",
    name: "Press prismatic ingot",
    description: "Master-tier pressing. One mistake and the shards shatter.",
    levelRequired: 75,
    durationMs: 6500,
    xpReward: 135,
    goldReward: 18,
    drops: [{ itemId: "prismatic_ingot", min: 1, max: 1, chance: 1 }],
  },

  {
    id: "tracking.foreshades",
    skillId: "tracking",
    name: "Track foreshades",
    description: "Follow blurred prints to a half-real predator.",
    levelRequired: 1,
    durationMs: 4000,
    xpReward: 14,
    goldReward: 2,
    drops: [{ itemId: "foreshade_hide", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "tracking.shellbacks",
    skillId: "tracking",
    name: "Track shellbacks",
    description: "Patient work — these beasts feel a footstep at fifty paces.",
    levelRequired: 35,
    durationMs: 5000,
    xpReward: 52,
    goldReward: 7,
    drops: [{ itemId: "shellback_carapace", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "tracking.aetherdrakes",
    skillId: "tracking",
    name: "Track aetherdrakes",
    description: "The largest beasts of the outer layers. Approach in silence.",
    levelRequired: 75,
    durationMs: 6500,
    xpReward: 130,
    goldReward: 16,
    drops: [
      { itemId: "aetherdrake_scale", min: 1, max: 1, chance: 1 },
      { itemId: "drake_heart", min: 1, max: 1, chance: 0.1 },
    ],
  },

  {
    id: "distilling.minor_tonic",
    skillId: "distilling",
    name: "Brew minor tonic",
    description: "Simple flora work over low heat.",
    levelRequired: 1,
    durationMs: 4000,
    xpReward: 16,
    goldReward: 2,
    drops: [{ itemId: "minor_tonic", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "distilling.sealing_draught",
    skillId: "distilling",
    name: "Brew sealing draught",
    description: "Used by Sealers. Steady the hand, slow the breath.",
    levelRequired: 35,
    durationMs: 5000,
    xpReward: 56,
    goldReward: 9,
    drops: [{ itemId: "sealing_draught", min: 1, max: 1, chance: 1 }],
  },
  {
    id: "distilling.prismatic_ink",
    skillId: "distilling",
    name: "Brew prismatic ink",
    description: "Cornerstone of high Sealing. Volatile, valuable.",
    levelRequired: 75,
    durationMs: 6500,
    xpReward: 138,
    goldReward: 18,
    drops: [{ itemId: "prismatic_ink", min: 1, max: 1, chance: 1 }],
  },

  {
    id: "sealing.dim_wisps",
    skillId: "sealing",
    name: "Banish dim wisps",
    description: "Bind small corruptions back into the lattice.",
    levelRequired: 1,
    durationMs: 5000,
    xpReward: 18,
    goldReward: 3,
    drops: [
      { itemId: "dim_token", min: 1, max: 1, chance: 1 },
      { itemId: "wisp_essence", min: 1, max: 1, chance: 0.05 },
    ],
  },
  {
    id: "sealing.sigilbreakers",
    skillId: "sealing",
    name: "Banish sigilbreakers",
    description: "Things made to undo binding. Bind them anyway.",
    levelRequired: 40,
    durationMs: 6000,
    xpReward: 75,
    goldReward: 10,
    drops: [
      { itemId: "bright_token", min: 1, max: 1, chance: 1 },
      { itemId: "sigilbreaker_core", min: 1, max: 1, chance: 0.04 },
    ],
  },
  {
    id: "sealing.voidrevenants",
    skillId: "sealing",
    name: "Banish void-revenants",
    description: "The hardest work in the discipline. Tokens hum afterward.",
    levelRequired: 80,
    durationMs: 7000,
    xpReward: 170,
    goldReward: 22,
    drops: [
      { itemId: "radiant_token", min: 1, max: 1, chance: 1 },
      { itemId: "revenant_heart", min: 1, max: 1, chance: 0.02 },
    ],
  },
];

export const ACTIONS: Record<string, ActionConfig> = Object.fromEntries(
  ACTIONS_LIST.map((a) => [a.id, a])
);

export function actionsForSkill(skillId: string): ActionConfig[] {
  return ACTIONS_LIST.filter((a) => a.skillId === skillId);
}

export function getAction(id: string): ActionConfig | undefined {
  return ACTIONS[id];
}
