export const GAME_ASSETS = {
  terrain: {
    grass: "/game/terrain/grassWhole.png",
    "grass-a": "/prooflayer-made/terrain/grass-a.png",
    "grass-b": "/prooflayer-made/terrain/grass-b.png",
    "grass-c": "/prooflayer-made/terrain/grass-c.png",
    dirt: "/game/terrain/dirt.png",
    "dirt-a": "/prooflayer-made/terrain/dirt-a.png",
    "dirt-b": "/prooflayer-made/terrain/dirt-b.png",
    "stone-a": "/prooflayer-made/terrain/stone-a.png",
    "stone-b": "/prooflayer-made/terrain/stone-b.png",
    dirtDouble: "/game/terrain/dirtDouble.png",
    water: "/game/terrain/water.png",
    "water-a": "/prooflayer-made/terrain/water-a.png",
    "water-b": "/prooflayer-made/terrain/water-b.png",
    riverNS: "/game/terrain/riverNS.png",
    riverEW: "/game/terrain/riverEW.png",
    bridgeNS: "/game/terrain/bridgeNS.png",
    bridgeEW: "/game/terrain/bridgeEW.png",
  },
  objects: {
    "tree-tall": "/game/objects/treeTall.png",
    "tree-alt-tall": "/game/objects/treeAltTall.png",
    "tree-short": "/game/objects/treeShort.png",
    "tree-alt-short": "/game/objects/treeAltShort.png",
    "conifer-tall": "/game/objects/coniferTall.png",
    "conifer-short": "/game/objects/coniferShort.png",
    "shard-rock": "/game/objects/shard-rock.png",
    barrel: "/game/objects/barrel.png",
    crate: "/game/objects/crate.png",
    chest: "/game/objects/chest.png",
    "fence-low-w": "/assets/Angle/fenceLow_W.png",
    "fence-low-e": "/assets/Angle/fenceLow_E.png",
    "fence-high-n": "/assets/Angle/fenceHigh_N.png",
    "fence-high-s": "/assets/Angle/fenceHigh_S.png",
    "fence-broken-n": "/assets/Angle/fenceLowBroken_N.png",
    "barrels-stack": "/assets/Angle/barrelsStacked_W.png",
    "sacks-crate": "/assets/Angle/sacksCrate_W.png",
    "hay-bales": "/assets/Angle/hayBales_W.png",
    "stone-w": "/assets/Angle/stone_W.png",
    "stone-side": "/assets/Angle/stoneSideUneven_W.png",
    "planks-w": "/assets/Angle/planks_W.png",
    "candle-stand": "/assets/Angle/candleStandDouble_W.png",
    "table-market": "/assets/Angle/tableShortChairs_W.png",
    "mine-cart-frame": "/prooflayer-made/blender-renders/mines/cart-frame.png",
    "mine-rail-straight": "/prooflayer-made/blender-renders/mines/rail-straight.png",
    "mine-rail-curve": "/prooflayer-made/blender-renders/mines/rail-curve.png",
    "mine-rock-a": "/prooflayer-made/blender-renders/mines/rock-cluster-a.png",
    "mine-rock-b": "/prooflayer-made/blender-renders/mines/rock-cluster-b.png",
    "mine-ore-rocks": "/prooflayer-made/blender-renders/mines/ore-rocks.png",
    "mine-door": "/prooflayer-made/blender-renders/mines/mine-door.png",
    "mine-bucket": "/prooflayer-made/blender-renders/mines/bucket.png",
    "mine-dynamite": "/prooflayer-made/blender-renders/mines/dynamite.png",
    "prop-axe": "/prooflayer-made/blender-renders/fantasy-props/axe-bronze.png",
    "prop-pickaxe": "/prooflayer-made/blender-renders/fantasy-props/pickaxe-bronze.png",
    "prop-coins": "/prooflayer-made/blender-renders/fantasy-props/coin-pile-large.png",
    "prop-potion-red": "/prooflayer-made/blender-renders/fantasy-props/potion-red.png",
    "prop-potion-blue": "/prooflayer-made/blender-renders/fantasy-props/potion-blue.png",
    "prop-scroll": "/prooflayer-made/blender-renders/fantasy-props/scroll-open.png",
    "prop-chest": "/prooflayer-made/blender-renders/fantasy-props/wood-chest.png",
    "prop-banner-blue": "/prooflayer-made/blender-renders/fantasy-props/banner-blue.png",
    "prop-banner-red": "/prooflayer-made/blender-renders/fantasy-props/banner-red.png",
    "prop-market-stall": "/prooflayer-made/blender-renders/fantasy-props/market-stall.png",
    "prop-cart-stall": "/prooflayer-made/blender-renders/fantasy-props/cart-stall.png",
    "prop-shield": "/prooflayer-made/blender-renders/fantasy-props/wood-shield.png",
    "prop-sword": "/prooflayer-made/blender-renders/fantasy-props/sword-bronze.png",
    "village-wagon": "/prooflayer-made/blender-renders/medieval-village/village-wagon.png",
    "village-fence": "/prooflayer-made/blender-renders/medieval-village/village-fence.png",
    "village-vine": "/prooflayer-made/blender-renders/medieval-village/village-vine.png",
    "village-shutters": "/prooflayer-made/blender-renders/medieval-village/village-shutters.png",
    "village-door-round": "/prooflayer-made/blender-renders/medieval-village/village-door-round.png",
    "qv-wagon": "/prooflayer-made/blender-renders/quaternius-village/qv-wagon.png",
    "qv-fence-single": "/prooflayer-made/blender-renders/quaternius-village/qv-fence-single.png",
    "qv-fence-extension": "/prooflayer-made/blender-renders/quaternius-village/qv-fence-extension.png",
    "qv-metal-fence": "/prooflayer-made/blender-renders/quaternius-village/qv-metal-fence.png",
    "qv-crate": "/prooflayer-made/blender-renders/quaternius-village/qv-crate.png",
    "qv-chimney": "/prooflayer-made/blender-renders/quaternius-village/qv-chimney.png",
    "qv-vine-a": "/prooflayer-made/blender-renders/quaternius-village/qv-vine-a.png",
    "qv-vine-b": "/prooflayer-made/blender-renders/quaternius-village/qv-vine-b.png",
    "qv-door-round": "/prooflayer-made/blender-renders/quaternius-village/qv-door-round.png",
    "qv-door-frame": "/prooflayer-made/blender-renders/quaternius-village/qv-door-frame.png",
    "qv-shutters-open": "/prooflayer-made/blender-renders/quaternius-village/qv-shutters-open.png",
    "qv-window-wide": "/prooflayer-made/blender-renders/quaternius-village/qv-window-wide.png",
    "qv-wall-door": "/prooflayer-made/blender-renders/quaternius-village/qv-wall-door.png",
    "qv-wall-window": "/prooflayer-made/blender-renders/quaternius-village/qv-wall-window.png",
    "qv-wall-plaster": "/prooflayer-made/blender-renders/quaternius-village/qv-wall-plaster.png",
    "qv-roof-flat-6x8": "/prooflayer-made/blender-renders/quaternius-village/qv-roof-flat-6x8.png",
    "qv-roof-round-6x8": "/prooflayer-made/blender-renders/quaternius-village/qv-roof-round-6x8.png",
    "qv-roof-tower": "/prooflayer-made/blender-renders/quaternius-village/qv-roof-tower.png",
    "qv-stairs": "/prooflayer-made/blender-renders/quaternius-village/qv-stairs.png",
    "qv-cottage": "/prooflayer-made/blender-renders/quaternius-prefabs/qv-cottage.png",
    "qv-market-house": "/prooflayer-made/blender-renders/quaternius-prefabs/qv-market-house.png",
    "qv-stone-shop": "/prooflayer-made/blender-renders/quaternius-prefabs/qv-stone-shop.png",
    "sign-apothecary": "/prooflayer-made/shop-signs/apothecary.png",
    "sign-forge": "/prooflayer-made/shop-signs/ember-forge.png",
    "sign-guild": "/prooflayer-made/shop-signs/prooflayer-guild.png",
    "sign-market": "/prooflayer-made/shop-signs/market-hall.png",
    "sign-quarry": "/prooflayer-made/shop-signs/quarry-camp.png",
    "nature-aether-stalk": "/prooflayer-made/blender-renders/nature/aether-stalk.png",
    "nature-dawn-bloom": "/prooflayer-made/blender-renders/nature/dawn-bloom.png",
    "nature-starflax": "/prooflayer-made/blender-renders/nature/starflax.png",
    "nature-silverflax": "/prooflayer-made/blender-renders/nature/silverflax.png",
    "nature-flower-bush": "/prooflayer-made/blender-renders/nature/flower-bush.png",
    "nature-mushroom": "/prooflayer-made/blender-renders/nature/mushroom.png",
    "nature-rock": "/prooflayer-made/blender-renders/nature/nature-rock.png",
    "tree-common-a": "/prooflayer-made/blender-renders/nature-trees/tree-common-a.png",
    "tree-common-b": "/prooflayer-made/blender-renders/nature-trees/tree-common-b.png",
    "tree-common-c": "/prooflayer-made/blender-renders/nature-trees/tree-common-c.png",
    "tree-pine-a": "/prooflayer-made/blender-renders/nature-trees/tree-pine-a.png",
    "tree-pine-b": "/prooflayer-made/blender-renders/nature-trees/tree-pine-b.png",
    "tree-pine-c": "/prooflayer-made/blender-renders/nature-trees/tree-pine-c.png",
    "tree-twisted": "/prooflayer-made/blender-renders/nature-trees/tree-twisted.png",
    "tree-dead": "/prooflayer-made/blender-renders/nature-trees/tree-dead.png",
    "animal-boar": "/prooflayer-made/blender-renders/wildlife/animal-boar.png",
    "animal-deer": "/prooflayer-made/blender-renders/wildlife/animal-deer.png",
    "animal-fox": "/prooflayer-made/blender-renders/wildlife/animal-fox.png",
    "animal-rabbit": "/prooflayer-made/blender-renders/wildlife/animal-rabbit.png",
    "animal-owl": "/prooflayer-made/blender-renders/wildlife/animal-owl.png",
    "medieval-well": "/prooflayer-made/blender-renders/medieval-props/medieval-well.png",
    "medieval-bench": "/prooflayer-made/blender-renders/medieval-props/medieval-bench.png",
    "medieval-firewood": "/prooflayer-made/blender-renders/medieval-props/medieval-firewood.png",
    "medieval-haystack": "/prooflayer-made/blender-renders/medieval-props/medieval-haystack.png",
    "medieval-pot-a": "/prooflayer-made/blender-renders/medieval-props/medieval-pot-a.png",
    "medieval-pot-b": "/prooflayer-made/blender-renders/medieval-props/medieval-pot-b.png",
    "medieval-trough": "/prooflayer-made/blender-renders/medieval-props/medieval-trough.png",
    "medieval-signpost": "/prooflayer-made/blender-renders/medieval-props/medieval-signpost.png",
    "medieval-stump": "/prooflayer-made/blender-renders/medieval-props/medieval-stump.png",
    "medieval-washboard": "/prooflayer-made/blender-renders/medieval-props/medieval-washboard.png",
    "medieval-basin": "/prooflayer-made/blender-renders/medieval-props/medieval-basin.png",
    "medieval-barrel-broken": "/prooflayer-made/blender-renders/medieval-props/medieval-barrel-broken.png",
  },
  buildings: {
    guild: "/prooflayer-made/blender-renders/medieval-houses/house-guild.png",
    market: "/prooflayer-made/blender-renders/medieval-houses/house-market.png",
    forge: "/prooflayer-made/blender-renders/medieval-houses/house-forge.png",
    chapel: "/prooflayer-made/blender-renders/medieval-houses/house-chapel.png",
    cottage: "/prooflayer-made/blender-renders/medieval-houses/house-cottage.png",
    roofBrown: "/game/buildings/roof-brown.png",
    roofRedA: "/game/buildings/roof-red-a.png",
    roofRedB: "/game/buildings/roof-red-b.png",
  },
} as const;

export const PLAYER_DIRECTIONS = Array.from({ length: 8 }, (_, direction) => ({
  direction,
  idle: `/game/characters/male/Male_${direction}_Idle0.png`,
  run: Array.from(
    { length: 10 },
    (_, frame) => `/game/characters/male/Male_${direction}_Run${frame}.png`
  ),
}));

export const PLAYER_WORK = Array.from(
  { length: 10 },
  (_, frame) => `/game/characters/male/Male_0_Pickup${frame}.png`
);
